# Serves the Jekyll landing site (_site) from the application process.
#
# WHY THIS EXISTS
#
# The static site used to be served by a SEPARATE nginx image (nginx.Dockerfile baked
# _site into nginx:1.27, nginx.conf served it at / and proxied /suites to this app).
# That layer bought nothing the app cannot do itself and cost a second image to build,
# tag, promote and keep in step with the app: every release produced an app image and a
# matching -nginx image, and a mismatch between them was a silent content skew. Serving
# the site from the app image makes the pair impossible to skew, drops a Deployment, a
# Service, a ConfigMap and a sidecar from the chart, and removes the nginx build from
# the release pipeline.
#
# SAME-ORIGIN IS THE POINT, NOT AN INCIDENTAL BENEFIT
#
# web/assets/scripts/config.js sets infernoHost to window.location.origin, so the kit
# pages POST to /suites/api/... on whatever host served them. That only works while the
# site and the API answer on ONE origin. nginx provided that origin by proxying; this
# middleware provides it by being in the same process. Nothing in the site needs to know
# which environment it is running in, which is what lets one image serve dev, prod and
# every preview.
#
# SEQUENCING (why nginx still exists while this does)
#
# The Helm chart renders from master the moment a PR merges, but the application image is
# pinned per environment and only advances on a separate promotion PR. An environment
# whose chart had dropped nginx while its image predated this file would have no landing
# page at all. So nginx.enabled defaults to false (dev and previews, which track master
# builds, pick this up immediately) and values-prod.yaml keeps it true until prod is
# promoted to an image containing _site. The nginx image, templates and sidecar are
# deleted in the follow-up change; see docs/nginx-removal.md.
#
# Implemented as middleware rather than a mounted app so it can sit above Inferno's
# RequestLogger and the OpenTelemetry handler: a page view or an asset fetch is answered
# and never forwarded, so it costs neither an access-log line nor a span. That is the
# same reasoning as HealthCheck, and it is why the ordering in config.ru matters.
#
# A missing root is a pass-through, not an error. _site is gitignored and generated by
# `bundle exec rake web:generate_dev`, so a fresh checkout has none; the app must still
# boot and serve /suites for anyone working on tests rather than on content.
module InfernoPlatformTemplate
  class StaticSite
    INDEX = 'index.html'.freeze

    # Mirrors the nginx.conf $cacheable map: images, scripts, styles and the favicon got
    # a day of browser caching, everything else (chiefly the generated HTML) was served
    # revalidate-always so a content deploy is visible immediately.
    CACHEABLE_EXTENSIONS = ['.png', '.svg', '.js', '.css', '.ico'].freeze
    CACHEABLE_CONTROL = 'public, max-age=86400'.freeze
    REVALIDATE_CONTROL = 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'.freeze

    SERVABLE_METHODS = ['GET', 'HEAD'].freeze

    # Paths this middleware must never answer. Resolving real files under _site would
    # already fall through for these, so this is cheap defence rather than correctness:
    # /suites is Inferno's mount point (BASE_PATH) and /healthz is HealthCheck's.
    RESERVED_PREFIXES = ['/suites', '/healthz'].freeze

    # nginx's default_type. Rack::Files otherwise labels an unknown extension text/plain,
    # which is worse than octet-stream for a file the browser should download.
    DEFAULT_MIME = 'application/octet-stream'.freeze

    def initialize(app, root: nil)
      @app = app
      @root = resolve_root(root)
      @files = Rack::Files.new(@root, {}, DEFAULT_MIME) if @root
    end

    def call(env)
      return @app.call(env) if @root.nil?
      return @app.call(env) unless SERVABLE_METHODS.include?(env['REQUEST_METHOD'])

      path = safe_path(env['PATH_INFO'])
      return @app.call(env) if path.nil? || reserved?(path)

      target = ::File.join(@root, path)

      if ::File.file?(target)
        serve(env, path)
      elsif ::File.file?(::File.join(target, INDEX))
        # Jekyll writes every page as a directory holding index.html (/about/index.html),
        # so /about has to become /about/ before the relative links inside that page
        # resolve. nginx did this with its own 301; keep the same status so any cached
        # redirect stays valid. The trailing slash is tested on the request's own
        # PATH_INFO because clean_path_info strips it.
        return directory_redirect(env) unless env['PATH_INFO'].to_s.end_with?('/')

        serve(env, ::File.join(path, INDEX))
      else
        @app.call(env)
      end
    end

    private

    def resolve_root(root)
      candidate = root || ENV['STATIC_SITE_ROOT']
      candidate = ::File.expand_path(::File.join(__dir__, '..', '..', '_site')) if candidate.nil? ||
                                                                                  candidate.empty?

      ::File.directory?(candidate) ? ::File.expand_path(candidate) : nil
    end

    # Returns a path that cannot escape the root, or nil if the request is not one this
    # middleware should look at. clean_path_info resolves '.' and '..' segments away
    # rather than rejecting them, so '/../../etc/passwd' normalises to '/etc/passwd' and
    # is simply looked up under _site, where it does not exist.
    def safe_path(path_info)
      raw = Rack::Utils.unescape_path(path_info.to_s)
      return nil unless Rack::Utils.valid_path?(raw)

      Rack::Utils.clean_path_info(raw)
    end

    def reserved?(path)
      RESERVED_PREFIXES.any? { |prefix| path == prefix || path.start_with?("#{prefix}/") }
    end

    # Rack::Files re-derives its target from PATH_INFO and unescapes it, so the path is
    # escaped again on the way in. Passing the already-unescaped path would corrupt any
    # filename containing a literal '%'.
    def serve(env, path)
      request_env = env.dup
      request_env['PATH_INFO'] = Rack::Utils.escape_path(path)

      status, headers, body = @files.call(request_env)
      headers['Cache-Control'] = cache_control(path)

      [status, headers, body]
    end

    # Note the request's own PATH_INFO is used, not the normalised one: the client should
    # land on the URL it asked for with a slash appended, not on a rewritten path.
    def directory_redirect(env)
      location = "#{env['PATH_INFO']}/"

      [301, { 'Location' => location, 'Content-Type' => 'text/plain', 'Cache-Control' => REVALIDATE_CONTROL },
       ["Moved Permanently: #{location}"]]
    end

    def cache_control(path)
      CACHEABLE_EXTENSIONS.include?(::File.extname(path).downcase) ? CACHEABLE_CONTROL : REVALIDATE_CONTROL
    end
  end
end
