services:
  inferno:
    build:
      context: ./
      args:
        BUNDLE_GEMFILE: Gemfile.dev
    mem_limit: 1500m
    restart: unless-stopped
    volumes:
      - ./Rakefile:/opt/inferno/Rakefile
      - ./web:/opt/inferno/web
      - ./resources:/opt/inferno/resources
      - ./_site:/opt/inferno/_site
