apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inferno-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/allow-snippet-annotations: "true"
    external-dns.alpha.kubernetes.io/hostname: "{{ join "," .Values.ingress.hostnames }}"
spec:
  ingressClassName: {{ .Values.controller.ingressClass }}
  tls:
    - hosts:
        {{- range .Values.ingress.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: inferno-tls
  rules:
    {{- range .Values.ingress.hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: /hl7validatorapi
            pathType: Prefix
            backend:
              service:
                name: validator-api
                port:
                  number: 3500
          ## uncomment to go back to serving pure inferno core without the nginx wrapper
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: inferno
          #       port:
          #         number: 4567
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
  {{- end }}
