ingress:
  hostnames:
    - development.inferno.sparked-fhir.com

inferno:
  imageUrl: ghcr.io/hl7au/au-fhir-inferno:8ee51f48c180445167e4d0b039f9df713b86ba5b-dev
  usesWrapper: true
  validatorImageUri: markiantorno/validator-wrapper:1.0.68
  replicas: 1
  workerReplicas: 1

validator:
  replicas: 1
  storageClassName: "gp3-encrypted"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

nginx:
  platformImageUri: ghcr.io/hl7au/au-fhir-inferno:8ee51f48c180445167e4d0b039f9df713b86ba5b-nginx-dev


externalSecrets:
  enabled: true
  roleArn: arn:aws:iam::471112546300:role/dev-inferno-external-secrets-sa
  secretArn: arn:aws:secretsmanager:ap-southeast-2:471112546300:secret:rds!db-ed54d45e-936a-4cf0-bdbb-9356864d6670-3FhA4J
  username: postgres
  region: ap-southeast-2

postgresql:
  externaldbhost: dev-inferno-postgresql.creaskuwcgs3.ap-southeast-2.rds.amazonaws.com
  global:
    postgresql:
      auth:
        database: inferno