apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-app
