apiVersion: v1
kind: Service
metadata:
  name: validator-api
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
  selector:
    app: validator-api
