name: Build and Release Inferno and Nginx Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        environment: [dev, prod]
        include:
          - environment: dev
            rake_task: web:generate_dev
            env_file: env.development
          - environment: prod
            rake_task: web:generate_prod
            env_file: .env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'

      - name: Install dependencies
        run: |
          bundle install

      - name: Use correct environment file
        run: cp ${{ matrix.env_file }} .env

      - name: Generate static content
        run: |
          bundle exec rake ${{ matrix.rake_task }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image (With commit hash)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.environment }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Nginx Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-nginx-${{ matrix.environment }}
